apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: lab
  project: default
  source:
    path: gitops/nginx
    repoURL: https://github.com/AurimasNav/lab-k3s.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true